name: "S3 CLI Action"
description: "CLI interface for interacting with an s3 compatible storage"
author: maya-hive
runs:
  using: docker
  image: Dockerfile
branding:
  icon: chevron-right
  color: gray-dark
